# Generated by Django 5.2 on 2025-10-16 20:15

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=230, unique=True)),
                ("excerpt", models.TextField(blank=True)),
                ("body", django_ckeditor_5.fields.CKEditor5Field()),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="If blank, falls back to title.",
                        max_length=70,
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Short summary for search engines.",
                        max_length=160,
                    ),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords (optional).",
                        max_length=255,
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seo/article_og/%Y/%m/%d/"
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional override; defaults to this page’s URL.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="articles/%Y/%m/%d/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
