# Generated by Django 5.2 on 2025-09-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="canonical_url",
            field=models.URLField(
                blank=True, help_text="Optional override; defaults to this page’s URL."
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="og_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="seo/article_og/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_description",
            field=models.CharField(
                blank=True,
                help_text="Short summary for search engines.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_keywords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords (optional).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_title",
            field=models.CharField(
                blank=True, help_text="If blank, falls back to title.", max_length=70
            ),
        ),
    ]
