# Generated by Django 5.2 on 2025-09-20 19:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_canonical_url_article_og_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
