# Generated by Django 5.2 on 2025-10-16 20:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("short_description", models.CharField(blank=True, max_length=50)),
                ("h1", models.CharField(blank=True, max_length=200)),
                ("h2", models.CharField(blank=True, max_length=200)),
                ("cta", models.CharField(blank=True, max_length=100)),
                ("description", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="services/icons/"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="services/images/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="If blank, falls back to name.",
                        max_length=70,
                    ),
                ),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("seo_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "og_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seo/product_og/"
                    ),
                ),
                ("canonical_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, default="fa-solid fa-check", max_length=80
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullets",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
