# Generated by Django 5.2 on 2025-10-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="cta",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="ServiceBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, default="fa-solid fa-check", max_length=80
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullets",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
