# Generated by Django 5.2 on 2025-10-16 20:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "features",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("short_description", models.CharField(blank=True, max_length=280)),
                ("description", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ("section_1", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                (
                    "image_1",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("caption_1", models.CharField(blank=True, max_length=255)),
                ("section_2", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("caption_2", models.CharField(blank=True, max_length=255)),
                ("section_3", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("caption_3", models.CharField(blank=True, max_length=255)),
                (
                    "general_features",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "specifications",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "downloads",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "accessories",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="If blank, falls back to name.",
                        max_length=70,
                    ),
                ),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("seo_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "og_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seo/product_og/"
                    ),
                ),
                ("canonical_url", models.URLField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
