# Generated by Django 5.2 on 2025-10-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="icons/categories/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="icons/products/"),
        ),
    ]
