# Generated by Django 5.2 on 2025-09-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="caption_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="caption_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="caption_3",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
