# Generated by Django 5.2 on 2025-10-16 21:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_icon_product_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="icons/categories/",
                validators=[core.validators.validate_svg_or_image],
            ),
        ),
    ]
