# Generated by Django 5.2 on 2025-10-02 21:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_accessories_product_downloads_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="features",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
    ]
